services:
  db:
    image: postgres:16-alpine
    container_name: invoice-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: invoice_generator
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: invoice-backend
    restart: always
    ports:
      - "8000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://postgres:admin123@db:5432/invoice_generator
      - JWT_SECRET=6XFA5ldcW463VPrbUCWqSftvHUKfb1cwlTZ6ZwgybWa
      - GOOGLE_CLIENT_ID=1017820093725-te751dt0okili4em79ifi00gcbcb2c4g.apps.googleusercontent.com
    depends_on:
      - db

  frontend:
    build:
      context: ./invoice
      args:
        - VITE_API_URL=http://93.127.198.5:8000/api
        - VITE_GOOGLE_CLIENT_ID=1017820093725-te751dt0okili4em79ifi00gcbcb2c4g.apps.googleusercontent.com
    container_name: invoice-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
